# Generated by Django 5.1.5 on 2025-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="context_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
