# Generated by Django 5.1.5 on 2025-03-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalityprofile",
            name="description",
            field=models.JSONField(),
        ),
    ]
