# Generated by Django 5.1.5 on 2025-03-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality_profiles", "0002_alter_personalityprofile_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalityprofile",
            name="description",
            field=models.TextField(),
        ),
    ]
