# Generated by Django 5.1.5 on 2025-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality_profiles", "0003_alter_personalityprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalityprofile",
            name="age_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("child", "Child (0-12)"),
                    ("teen", "Teenager (13-19)"),
                    ("young_adult", "Young Adult (20-35)"),
                    ("adult", "Adult (36-50)"),
                    ("senior", "Senior (51+)"),
                    ("unknown", "Unknown/Not specified"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=2,
                null=True,
            ),
        ),
    ]
