# Generated by Django 5.1.5 on 2025-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality_profiles", "0004_personalityprofile_age_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalityprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="character_images/"
            ),
        ),
    ]
